export { default as default } from './http-client';
export { authAPI } from './auth.api';
export { adminAPI, adminAPI_ext } from './admin.api';
export { coursesAPI } from './courses.api';
export { routinesAPI } from './routines.api';
export { platformsAPI } from './platforms.api';
export { filesAPI } from './files.api';
export { announcementsAPI } from './announcements.api';
export { templatesAPI } from './templates.api';
export { bulkAPI } from './bulk.api';
export { logsAPI } from './logs.api';
export { studentsAPI } from './students.api';
export { examRoutinesAPI } from './examRoutines.api';
export { attendanceAPI } from './attendance.api';
export { canvaAPI } from './canva.api';
