const db = require('../config/database');
const fs = require('fs');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');

// Initialize Supabase if credentials are provided
let supabase = null;
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_ANON_KEY;
const bucketName = process.env.SUPABASE_BUCKET_NAME || 'announcement-files';

if (supabaseUrl && supabaseKey) {
    console.log('Supabase Storage configurations detected. Initializing Supabase client...');
    const cleanSupabaseUrl = supabaseUrl.replace(/\/rest\/v1\/?$/, '').replace(/\/+$/, '');
    supabase = createClient(cleanSupabaseUrl, supabaseKey);
} else {
    console.log('⚠️ Supabase credentials missing. File service will run on local uploads fallback.');
}

const isVercel = !!process.env.VERCEL;
const uploadsDir = isVercel
    ? '/tmp/uploads'
    : path.join(__dirname, '../../../uploads');

if (!fs.existsSync(uploadsDir)) {
    try {
        fs.mkdirSync(uploadsDir, { recursive: true });
    } catch (err) {
        console.error('Failed to create uploads directory:', err.message);
    }
}

// Helper to calculate expiry date (15 days from now)
function getExpiryDate() {
    const days = parseInt(process.env.FILE_EXPIRY_DAYS || '15');
    const date = new Date();
    date.setDate(date.getDate() + days);
    return date.toISOString();
}

async function uploadFile(file, userId) {
    const originalName = file.originalname;
    const fileType = file.mimetype;
    let fileSize = file.size;
    const expiresAt = getExpiryDate();
    
    // Image Compression logic
    const fileTypeLower = fileType.toLowerCase();
    const isImage = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'].includes(fileTypeLower);
    
    if (isImage) {
        try {
            const sharp = require('sharp');
            const imageQuality = parseInt(process.env.IMAGE_QUALITY || '80');
            const pngCompression = parseInt(process.env.PNG_COMPRESSION_LEVEL || '9');
            
            let pipeline = sharp(file.path).rotate();
            
            if (fileTypeLower === 'image/jpeg' || fileTypeLower === 'image/jpg') {
                pipeline = pipeline.jpeg({ quality: imageQuality });
            } else if (fileTypeLower === 'image/png') {
                pipeline = pipeline.png({ compressionLevel: pngCompression, palette: true });
            } else if (fileTypeLower === 'image/webp') {
                pipeline = pipeline.webp({ quality: imageQuality });
            }
            
            const compressedBuffer = await pipeline.toBuffer();
            fs.writeFileSync(file.path, compressedBuffer);
            fileSize = compressedBuffer.length;
            console.log(`[Image Compression] Compressed image "${originalName}" from ${file.size} to ${fileSize} bytes.`);
        } catch (compressErr) {
            console.error('[Image Compression] Failed to compress image:', compressErr.message);
        }
    }
    
    let storagePath = '';
    
    if (supabase) {
        // Generate unique filename for Supabase
        const uniqueName = `${Date.now()}-${originalName.replace(/\s+/g, '_')}`;
        const fileBuffer = fs.readFileSync(file.path);
        
        const { data, error } = await supabase.storage
            .from(bucketName)
            .upload(uniqueName, fileBuffer, {
                contentType: fileType,
                duplex: 'half'
            });
            
        if (error) {
            console.error('Supabase upload error:', error.message);
            throw new Error(`Supabase upload failed: ${error.message}`);
        }
        
        storagePath = data.path;
        
        // Clean up temporary local file generated by multer
        try {
            fs.unlinkSync(file.path);
        } catch (err) {
            console.error('Failed to delete temp multer file:', err);
        }
    } else {
        // If local fallback, move the file from temp to final uploads directory
        const uniqueName = `${Date.now()}-${originalName.replace(/\s+/g, '_')}`;
        const finalPath = path.join(uploadsDir, uniqueName);
        
        fs.renameSync(file.path, finalPath);
        storagePath = uniqueName; // Local filename is stored
    }

    // Insert file metadata into database
    const result = await db.query(
        'INSERT INTO files (original_name, storage_path, file_type, file_size, uploaded_by, expires_at) VALUES ($1, $2, $3, $4, $5, $6) RETURNING *',
        [originalName, storagePath, fileType, fileSize, userId, expiresAt]
    );

    return result.rows[0];
}

async function getFileUrl(fileId, hostUrl = '') {
    const result = await db.query('SELECT * FROM files WHERE id = $1 AND is_deleted = false', [fileId]);
    if (result.rows.length === 0) {
        throw new Error('File not found or has expired');
    }
    
    const file = result.rows[0];
    
    if (supabase) {
        // Generate signed URL (expires in 1 hour)
        const { data, error } = await supabase.storage
            .from(bucketName)
            .createSignedUrl(file.storage_path, 3600);
            
        if (error) {
            console.error('Supabase signed URL error:', error.message);
            throw new Error(`Failed to generate download URL: ${error.message}`);
        }
        return {
            url: data.signedUrl,
            file
        };
    } else {
        // Local download URL
        const cleanHost = hostUrl.replace(/\/$/, '');
        return {
            url: `${cleanHost}/uploads/${file.storage_path}`,
            file
        };
    }
}

async function deleteFile(fileId) {
    const result = await db.query('SELECT * FROM files WHERE id = $1 AND is_deleted = false', [fileId]);
    if (result.rows.length === 0) {
        return false;
    }
    
    const file = result.rows[0];
    
    if (supabase) {
        const { error } = await supabase.storage
            .from(bucketName)
            .remove([file.storage_path]);
            
        if (error) {
            console.error('Failed to remove file from Supabase storage:', error.message);
        }
    } else {
        const filePath = path.join(uploadsDir, file.storage_path);
        if (fs.existsSync(filePath)) {
            try {
                fs.unlinkSync(filePath);
            } catch (err) {
                console.error('Failed to remove local file from disk:', err.message);
            }
        }
    }
    
    // Mark as deleted in database
    await db.query('UPDATE files SET is_deleted = true WHERE id = $1', [fileId]);
    return true;
}

// Daily Cron cleanup function
async function cleanupExpiredFiles() {
    console.log('⏰ Starting expired files cleanup job...');
    const result = await db.query('SELECT * FROM expired_files');
    const expired = result.rows;
    
    console.log(`Found ${expired.length} expired files to delete.`);
    
    let count = 0;
    for (const file of expired) {
        try {
            await deleteFile(file.id);
            count++;
        } catch (err) {
            console.error(`Error deleting file ID ${file.id} (${file.original_name}):`, err.message);
        }
    }
    
    console.log(`✅ Cleanup completed. Deleted ${count}/${expired.length} files.`);
    return { found: expired.length, deleted: count };
}

async function getStorageUsage() {
    const result = await db.query('SELECT COALESCE(SUM(file_size), 0) as used_bytes FROM files WHERE is_deleted = false');
    const usedBytes = parseInt(result.rows[0].used_bytes, 10);
    const limitBytes = parseInt(process.env.STORAGE_LIMIT_BYTES || '104857600', 10); // default to 100MB
    const percentage = limitBytes > 0 ? parseFloat(((usedBytes / limitBytes) * 100).toFixed(2)) : 0;
    
    return {
        usedBytes,
        limitBytes,
        percentage
    };
}

module.exports = {
    uploadFile,
    getFileUrl,
    deleteFile,
    cleanupExpiredFiles,
    getStorageUsage,
    uploadsDir
};
